#!/bin/sh

# ANTHROPIC_*/CLAUDE_*/GH_*/GITHUB_*/npm_config_* の環境変数をログインシェル用に保存
# (値はダブルクォートで包む。値に空白があっても 1 つの値として扱われる)
{
  echo "# generated by entrypoint.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  env | grep -E '^(ANTHROPIC_|CLAUDE_|GH_|GITHUB_|npm_config_)' | while IFS='=' read -r k v; do
    esc=$(printf '%s' "$v" | sed 's/\\/\\\\/g; s/"/\\"/g')
    printf 'export %s="%s"\n' "$k" "$esc"
  done
} > /etc/profile.d/agent-env.sh
chmod 644 /etc/profile.d/agent-env.sh

# docker run … bash のように引数があるときはそれを exec で起動(従来の入室方法を維持)
if [ "$#" -gt 0 ]; then
  exec "$@"
fi

# 引数なし(docker run -d 等)のときは sshd をフォアグラウンド起動
exec /usr/sbin/sshd -D -e